# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FuzzyJoin
                                 A QGIS plugin
 Join tables using min Damerau-Levenshtein distance
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-09
        copyright            : (C) 2023 by Zoltán Siki
        email                : siki1958@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FuzzyJoin class from file FuzzyJoin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fuzzy_join import FuzzyJoin
    return FuzzyJoin(iface)
